version: "3.4"

x-app: &app
  image: ${image_name}
  depends_on:
    - redis
    - postgres
  environment: &appEnv
    ENV: dev
    DATABASE_URL: ${DATABASE_URL}
    REDIS_URL: ${REDIS_URL}
    PORT: 3000
  entrypoint: sh -c "echo $DATABASE_URL && npx prisma db push && npm run nodemon"
  volumes:
    - ..:/app

services:
  bot:
    <<: *app
    environment:
      <<: *appEnv
      APP: BOT

  api:
    <<: *app
    depends_on:
      - bot
    environment:
      <<: *appEnv
      APP: API
    ports:
      - 3000:3000

  postgres:
    image: postgres:alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: debug
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis
    expose:
      - 6379
    ports:
      - 6379:6379

  tests:
    profiles:
      - test
    image: ${image_name}
    depends_on:
      - test_mongo
      - redis
    environment:
      ENV: test
      MONGO_URL: postgres://postgres:postgres@test_postgres:27017/
      REDIS_URL: redis://redis:6379/0
    volumes:
      - ..:/app

  test_postgres:
    profiles:
      - test
    image: postgres:alpine
    environment:
      POSTGRES_DB: test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

volumes:
  mongo:
